export const PACKAGE_NAME = "@ai-oss/db" as const;

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export const PHASE_01_TABLES = [
  "profiles",
  "user_settings",
  "user_security_state",
  "consent_events",
  "roles",
  "role_bindings",
  "permission_audit",
  "zones",
  "zone_members",
  "zone_flairs",
  "zone_wiki_pages",
  "zone_settings",
  "zone_governance_settings",
  "posts",
  "comments",
  "votes",
  "papers",
  "paper_versions",
  "paper_authors",
  "paper_files",
  "paper_links",
  "paper_reviews",
  "replication_reports",
  "chat_rooms",
  "chat_room_members",
  "chat_messages",
  "voice_rooms",
  "voice_participants",
  "reports",
  "moderation_actions",
  "appeals",
  "automod_rules",
  "automod_runs",
  "mod_removal_petitions",
  "mod_removal_petition_support",
  "governance_votes",
  "governance_ballots",
  "files",
  "search_documents",
  "donations",
  "stripe_events",
  "audit_events",
  "security_events",
  "observability_events",
  "alert_events",
  "system_health_snapshots",
  "privacy_requests",
  "legal_requests",
  "transparency_report_events",
  "abuse_rate_limit_events",
] as const;

export type TableName = (typeof PHASE_01_TABLES)[number];

export const TABLE_COLUMNS = {
  profiles: [
    "id",
    "username",
    "display_name",
    "avatar_file_id",
    "bio",
    "website_url",
    "github_username",
    "orcid",
    "affiliation",
    "research_interests",
    "profile_visibility",
    "email_visibility",
    "contact_permission",
    "search_indexing_enabled",
    "contribution_summary",
    "reputation_score",
    "trust_score",
    "public_reputation",
    "donor_badge_visible",
    "moderator_badge_visible",
    "admin_badge_visible",
    "suspended_at",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
  ],
  user_settings: [
    "user_id",
    "privacy",
    "notifications",
    "cookie_consent",
    "cookie_consent_updated_at",
    "gpc_signal",
    "do_not_sell_share",
    "limit_sensitive_data",
    "analytics_consent",
    "email_digest_frequency",
    "public_donor_badge_opt_in",
    "dm_permissions",
    "created_at",
    "updated_at",
  ],
  user_security_state: [
    "user_id",
    "mfa_enrolled",
    "passkey_enrolled",
    "elevated_mfa_required",
    "suspicious_login_count",
    "last_login_at",
    "last_login_ip",
    "session_revoked_before",
    "risk_level",
    "trust_score",
    "risk_score",
    "risk_factors",
    "device_risk",
    "bot_challenge_until",
    "mfa_verified_at",
    "passkey_verified_at",
    "step_up_verified_at",
    "admin_session_started_at",
    "admin_session_expires_at",
    "last_admin_ip_hash",
    "session_risk",
    "break_glass_enabled",
    "break_glass_last_used_at",
    "break_glass_monitored_at",
    "waf_bypass_until",
    "created_at",
    "updated_at",
  ],
  security_events: [
    "id",
    "actor_id",
    "action",
    "severity",
    "reason",
    "ip_hash",
    "device_hash",
    "user_agent",
    "route",
    "waf_rule_key",
    "metadata",
    "monitoring_required",
    "post_incident_review_required",
    "created_at",
  ],
  observability_events: [
    "id",
    "event_type",
    "metric_key",
    "value",
    "unit",
    "log_level",
    "event_name",
    "message",
    "tags",
    "metadata",
    "correlation_id",
    "redaction_applied",
    "occurred_at",
    "created_at",
  ],
  alert_events: [
    "id",
    "alert_key",
    "severity",
    "status",
    "threshold",
    "observed_value",
    "runbook_slug",
    "correlation_id",
    "metadata",
    "fired_at",
    "resolved_at",
    "created_at",
  ],
  system_health_snapshots: [
    "id",
    "overall_status",
    "components",
    "source",
    "metadata",
    "created_at",
  ],
  consent_events: [
    "id",
    "user_id",
    "policy_key",
    "policy_version",
    "accepted",
    "age_attested",
    "ip_address",
    "user_agent",
    "metadata",
    "created_at",
  ],
  roles: [
    "id",
    "role_key",
    "name",
    "description",
    "role_type",
    "permissions",
    "system_role",
    "created_by",
    "created_at",
    "updated_at",
  ],
  role_bindings: [
    "id",
    "role_id",
    "user_id",
    "zone_id",
    "granted_by",
    "grant_reason",
    "expires_at",
    "revoked_at",
    "created_at",
    "updated_at",
  ],
  permission_audit: [
    "id",
    "actor_id",
    "target_user_id",
    "role_id",
    "zone_id",
    "action",
    "previous_state",
    "new_state",
    "reason",
    "correlation_id",
    "created_at",
  ],
  zones: [
    "id",
    "slug",
    "name",
    "description",
    "visibility",
    "status",
    "created_by",
    "default_post_visibility",
    "moderation_status",
    "deleted_at",
    "created_at",
    "updated_at",
  ],
  zone_members: [
    "zone_id",
    "user_id",
    "member_role",
    "status",
    "moderator_tier",
    "moderator_selection_source",
    "moderator_status",
    "moderator_status_reason",
    "moderator_since",
    "moderator_updated_by",
    "joined_at",
    "updated_at",
  ],
  zone_flairs: ["id", "zone_id", "label", "color", "description", "applies_to", "created_at"],
  zone_wiki_pages: [
    "id",
    "zone_id",
    "slug",
    "title",
    "body",
    "version",
    "edited_by",
    "visibility",
    "deleted_at",
    "created_at",
    "updated_at",
  ],
  zone_settings: [
    "zone_id",
    "post_permissions",
    "automod_config",
    "ranking_config",
    "chat_config",
    "updated_by",
    "updated_at",
  ],
  zone_governance_settings: [
    "zone_id",
    "petition_threshold",
    "vote_duration",
    "quorum_percent",
    "removal_threshold_percent",
    "certification_required",
    "updated_by",
    "updated_at",
  ],
  posts: [
    "id",
    "zone_id",
    "author_id",
    "post_type",
    "title",
    "url",
    "body",
    "markdown",
    "flair_id",
    "tags",
    "visibility",
    "status",
    "moderation_status",
    "removal_reason",
    "is_locked",
    "score",
    "certified_score",
    "comment_count",
    "vote_visibility_until",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
    "tsv",
  ],
  comments: [
    "id",
    "post_id",
    "paper_id",
    "paper_version_id",
    "parent_comment_id",
    "author_id",
    "body",
    "markdown",
    "edit_history",
    "status",
    "moderation_status",
    "removal_reason",
    "is_locked",
    "score",
    "certified_score",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
    "tsv",
  ],
  votes: [
    "id",
    "user_id",
    "target_type",
    "target_id",
    "value",
    "is_certified",
    "certified_at",
    "certification_reason",
    "certification_status",
    "suspicious_score",
    "anomaly_reasons",
    "created_at",
    "updated_at",
  ],
  papers: [
    "id",
    "identifier",
    "submitter_id",
    "zone_id",
    "title",
    "abstract",
    "categories",
    "tags",
    "license",
    "ai_metadata",
    "status",
    "current_version_number",
    "safety_status",
    "moderation_status",
    "not_peer_reviewed_label_acknowledged",
    "legal_hold",
    "withdrawn_at",
    "removed_at",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
    "tsv",
  ],
  paper_versions: [
    "id",
    "paper_id",
    "version_number",
    "submitter_id",
    "status",
    "title_snapshot",
    "abstract_snapshot",
    "full_text_snapshot",
    "metadata_snapshot",
    "license_snapshot",
    "file_hashes",
    "text_diff_from_previous",
    "submitted_at",
    "published_at",
    "withdrawn_at",
    "created_at",
  ],
  paper_authors: [
    "id",
    "paper_id",
    "profile_id",
    "author_name",
    "author_slug",
    "author_order",
    "affiliation",
    "orcid",
    "is_submitter",
    "is_corresponding",
    "anonymized_at",
    "created_at",
  ],
  paper_files: [
    "id",
    "paper_id",
    "paper_version_id",
    "file_id",
    "file_kind",
    "immutable",
    "created_at",
  ],
  paper_links: ["id", "paper_id", "link_type", "url", "label", "created_at"],
  paper_reviews: [
    "id",
    "paper_id",
    "paper_version_id",
    "reviewer_id",
    "review_type",
    "clarity_score",
    "novelty_score",
    "methodology_score",
    "reproducibility_score",
    "safety_score",
    "evidence_score",
    "body",
    "status",
    "moderation_status",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
  ],
  replication_reports: [
    "id",
    "paper_id",
    "paper_version_id",
    "reporter_id",
    "environment",
    "hardware",
    "data_snapshot",
    "commit_hash",
    "result_status",
    "notes",
    "status",
    "moderation_status",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
  ],
  chat_rooms: [
    "id",
    "zone_id",
    "room_type",
    "title",
    "description",
    "visibility",
    "is_private",
    "created_by",
    "linked_post_id",
    "linked_paper_id",
    "locked_at",
    "slow_mode_seconds",
    "rules",
    "deleted_at",
    "created_at",
    "updated_at",
  ],
  chat_room_members: [
    "room_id",
    "user_id",
    "member_role",
    "status",
    "last_read_at",
    "joined_at",
    "updated_at",
  ],
  chat_messages: [
    "id",
    "room_id",
    "author_id",
    "parent_message_id",
    "body",
    "markdown",
    "attachment_file_ids",
    "edit_history",
    "status",
    "moderation_status",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
  ],
  voice_rooms: [
    "id",
    "zone_id",
    "chat_room_id",
    "room_type",
    "livekit_room_name",
    "title",
    "visibility",
    "created_by",
    "is_active",
    "recording_enabled",
    "transcription_enabled",
    "locked_at",
    "waiting_room_enabled",
    "screen_share_enabled",
    "metadata",
    "ended_at",
    "created_at",
    "updated_at",
  ],
  voice_participants: [
    "id",
    "voice_room_id",
    "user_id",
    "participant_role",
    "joined_at",
    "left_at",
    "muted_at",
    "banned_at",
    "deafen_at",
    "push_to_talk_enabled",
    "cooldown_until",
    "metadata",
  ],
  reports: [
    "id",
    "reporter_id",
    "target_type",
    "target_id",
    "zone_id",
    "reason",
    "details",
    "status",
    "severity",
    "source",
    "report_count",
    "metadata",
    "assigned_to",
    "created_at",
    "updated_at",
  ],
  moderation_actions: [
    "id",
    "actor_id",
    "target_type",
    "target_id",
    "zone_id",
    "action_type",
    "reason",
    "previous_state",
    "new_state",
    "expires_at",
    "automated",
    "correlation_id",
    "appealable",
    "statement_of_reasons",
    "created_at",
  ],
  appeals: [
    "id",
    "moderation_action_id",
    "appellant_id",
    "body",
    "status",
    "evidence",
    "decision",
    "decision_reason",
    "audit_trail",
    "reviewed_by",
    "reviewed_at",
    "created_at",
    "updated_at",
  ],
  automod_rules: [
    "id",
    "zone_id",
    "name",
    "rule_type",
    "config",
    "action",
    "enabled",
    "severity",
    "rule_key",
    "description",
    "yaml",
    "version",
    "status",
    "published_at",
    "last_validated_at",
    "rollback_of",
    "created_by",
    "created_at",
    "updated_at",
  ],
  automod_runs: [
    "id",
    "rule_id",
    "zone_id",
    "target_type",
    "target_id",
    "status",
    "action_taken",
    "score",
    "details",
    "input_snapshot",
    "result",
    "created_at",
  ],
  mod_removal_petitions: [
    "id",
    "zone_id",
    "target_user_id",
    "created_by",
    "reason",
    "status",
    "support_count",
    "support_threshold",
    "eligibility_snapshot",
    "public_reason",
    "outcome_reason",
    "qualified_at",
    "opened_vote_id",
    "created_at",
    "updated_at",
  ],
  mod_removal_petition_support: [
    "petition_id",
    "user_id",
    "eligibility_snapshot",
    "risk_snapshot",
    "suspicious_score",
    "created_at",
  ],
  governance_votes: [
    "id",
    "zone_id",
    "subject_type",
    "subject_id",
    "title",
    "description",
    "status",
    "opens_at",
    "closes_at",
    "created_by",
    "certified_by",
    "certified_at",
    "certification_status",
    "certification_reason",
    "aggregate_tally",
    "public_result",
    "quorum_percent",
    "removal_threshold_percent",
    "certification_required",
    "admin_review_reason",
    "frozen_at",
    "frozen_by",
    "invalidated_at",
    "invalidated_by",
    "brigading_mitigation",
    "quorum_adjustment_percent",
    "created_at",
    "updated_at",
  ],
  governance_ballots: [
    "id",
    "governance_vote_id",
    "user_id",
    "choice",
    "weight",
    "ballot_hash",
    "eligibility_snapshot",
    "risk_snapshot",
    "is_certified",
    "certified_at",
    "suspicious_score",
    "certification_reason",
    "anomaly_reasons",
    "created_at",
  ],
  files: [
    "id",
    "owner_id",
    "provider",
    "storage_key",
    "filename",
    "content_type",
    "size_bytes",
    "sha256",
    "visibility",
    "zone_id",
    "scan_status",
    "moderation_status",
    "metadata",
    "deleted_at",
    "anonymized_at",
    "created_at",
    "updated_at",
  ],
  search_documents: [
    "id",
    "target_type",
    "target_id",
    "visibility",
    "zone_id",
    "title",
    "body",
    "metadata",
    "embedding",
    "embedding_status",
    "indexed_at",
    "is_fresh",
    "source_updated_at",
    "deleted_at",
    "created_at",
    "updated_at",
    "tsv",
  ],
  donations: [
    "id",
    "user_id",
    "stripe_customer_id",
    "stripe_checkout_session_id",
    "stripe_payment_intent_id",
    "stripe_subscription_id",
    "amount_cents",
    "currency",
    "status",
    "mode",
    "anonymous",
    "donor_badge_opt_in",
    "donor_badge_issued_at",
    "checkout_url",
    "receipt_email",
    "retention_reason",
    "accounting_exported_at",
    "failure_code",
    "chargeback_status",
    "stripe_last_event_id",
    "stripe_last_event_type",
    "accounting_metadata",
    "refunded_at",
    "created_at",
    "updated_at",
  ],
  stripe_events: [
    "id",
    "event_type",
    "payload",
    "donation_id",
    "idempotency_key",
    "processed_at",
    "processing_error",
    "created_at",
  ],
  audit_events: [
    "id",
    "actor_id",
    "actor_role",
    "action",
    "resource_type",
    "resource_id",
    "zone_id",
    "previous_state",
    "new_state",
    "reason",
    "request_ip",
    "device_metadata",
    "correlation_id",
    "automated",
    "created_at",
  ],
  privacy_requests: [
    "id",
    "user_id",
    "request_type",
    "status",
    "jurisdiction",
    "due_at",
    "verification_status",
    "gpc_signal",
    "do_not_sell_share",
    "limit_sensitive_data",
    "outcome_summary",
    "denied_reason",
    "completed_by",
    "details",
    "export_file_id",
    "requested_at",
    "completed_at",
    "updated_at",
  ],
  legal_requests: [
    "id",
    "requester",
    "requester_email",
    "request_type",
    "target_type",
    "target_id",
    "target_url",
    "status",
    "jurisdiction",
    "legal_hold",
    "due_at",
    "source",
    "priority",
    "notice_category",
    "statement_of_reasons",
    "notification_status",
    "audit_metadata",
    "resolved_by",
    "child_safety_escalation",
    "details",
    "received_at",
    "closed_at",
    "updated_at",
  ],
  transparency_report_events: [
    "id",
    "event_type",
    "subject_type",
    "subject_id",
    "privacy_request_id",
    "legal_request_id",
    "moderation_action_id",
    "zone_id",
    "public_bucket",
    "region",
    "outcome",
    "published_at",
    "count_delta",
    "metadata",
    "is_public",
    "occurred_at",
    "created_at",
  ],
  abuse_rate_limit_events: [
    "id",
    "actor_id",
    "action",
    "bucket",
    "allowed",
    "reason",
    "ip_hash",
    "device_hash",
    "bot_score",
    "metadata",
    "created_at",
  ],
} as const satisfies Record<TableName, readonly string[]>;

export type TableColumn<TTable extends TableName> = (typeof TABLE_COLUMNS)[TTable][number];

export const UNIQUE_CONSTRAINTS = {
  votes: [["user_id", "target_type", "target_id"]],
  paper_versions: [["paper_id", "version_number"]],
  governance_ballots: [["governance_vote_id", "user_id"]],
  abuse_rate_limit_events: [],
  mod_removal_petition_support: [["petition_id", "user_id"]],
  role_bindings: [["role_id", "user_id", "zone_id"]],
  search_documents: [["target_type", "target_id"]],
  files: [["provider", "storage_key"]],
} as const;

export const PROTECTED_COLUMNS = {
  profiles: [
    "reputation_score",
    "trust_score",
    "public_reputation",
    "moderator_badge_visible",
    "admin_badge_visible",
    "suspended_at",
  ],
  user_security_state: [
    "trust_score",
    "risk_score",
    "risk_factors",
    "device_risk",
    "mfa_verified_at",
    "passkey_verified_at",
    "step_up_verified_at",
    "admin_session_started_at",
    "admin_session_expires_at",
    "last_admin_ip_hash",
    "session_risk",
    "break_glass_enabled",
    "break_glass_last_used_at",
    "break_glass_monitored_at",
    "waf_bypass_until",
  ],
  security_events: ["severity", "ip_hash", "device_hash", "metadata"],
  observability_events: ["message", "tags", "metadata", "correlation_id"],
  alert_events: ["severity", "metadata", "correlation_id"],
  system_health_snapshots: ["components", "metadata"],
  zone_members: [
    "member_role",
    "status",
    "moderator_tier",
    "moderator_selection_source",
    "moderator_status",
    "moderator_status_reason",
    "moderator_since",
    "moderator_updated_by",
  ],
  posts: ["score", "certified_score", "comment_count", "moderation_status"],
  comments: ["score", "certified_score", "moderation_status"],
  votes: [
    "is_certified",
    "certified_at",
    "certification_reason",
    "certification_status",
    "suspicious_score",
    "anomaly_reasons",
  ],
  abuse_rate_limit_events: [],
  papers: ["safety_status", "moderation_status", "legal_hold", "ai_metadata"],
  files: ["scan_status", "moderation_status", "sha256", "size_bytes"],
  mod_removal_petitions: [
    "status",
    "support_count",
    "support_threshold",
    "eligibility_snapshot",
    "outcome_reason",
    "qualified_at",
    "opened_vote_id",
  ],
  mod_removal_petition_support: ["eligibility_snapshot", "risk_snapshot", "suspicious_score"],
  governance_votes: [
    "status",
    "certified_by",
    "certified_at",
    "certification_status",
    "certification_reason",
    "aggregate_tally",
    "public_result",
    "quorum_percent",
    "removal_threshold_percent",
    "certification_required",
    "admin_review_reason",
    "frozen_at",
    "frozen_by",
    "invalidated_at",
    "invalidated_by",
    "brigading_mitigation",
    "quorum_adjustment_percent",
  ],
  governance_ballots: [
    "weight",
    "ballot_hash",
    "eligibility_snapshot",
    "risk_snapshot",
    "is_certified",
    "certified_at",
    "suspicious_score",
    "certification_reason",
    "anomaly_reasons",
  ],
  donations: [
    "status",
    "amount_cents",
    "stripe_customer_id",
    "stripe_checkout_session_id",
    "stripe_payment_intent_id",
    "stripe_subscription_id",
    "donor_badge_issued_at",
    "accounting_exported_at",
    "failure_code",
    "chargeback_status",
    "stripe_last_event_id",
    "stripe_last_event_type",
    "refunded_at",
  ],
  privacy_requests: [
    "status",
    "due_at",
    "verification_status",
    "outcome_summary",
    "denied_reason",
    "completed_by",
    "completed_at",
  ],
  legal_requests: [
    "status",
    "legal_hold",
    "due_at",
    "priority",
    "statement_of_reasons",
    "notification_status",
    "audit_metadata",
    "resolved_by",
    "closed_at",
  ],
  audit_events: ["previous_state", "new_state", "reason"],
} as const;

export const ADMIN_ONLY_TABLES = [
  "permission_audit",
  "moderation_actions",
  "automod_runs",
  "stripe_events",
  "audit_events",
  "observability_events",
  "alert_events",
  "system_health_snapshots",
  "legal_requests",
  "abuse_rate_limit_events",
] as const satisfies readonly TableName[];

export const APPEND_ONLY_TABLES = [
  "consent_events",
  "permission_audit",
  "moderation_actions",
  "audit_events",
  "transparency_report_events",
  "abuse_rate_limit_events",
  "security_events",
  "observability_events",
  "alert_events",
  "system_health_snapshots",
] as const satisfies readonly TableName[];

export const USER_ACCESSIBLE_TABLES = PHASE_01_TABLES.filter(
  (table) => !ADMIN_ONLY_TABLES.includes(table as (typeof ADMIN_ONLY_TABLES)[number]),
);

export interface DatabaseTableMetadata {
  name: TableName;
  columns: readonly string[];
  protectedColumns: readonly string[];
  uniqueConstraints: readonly (readonly string[])[];
  appendOnly: boolean;
  adminOnly: boolean;
}

export function getTableMetadata(table: TableName): DatabaseTableMetadata {
  return {
    name: table,
    columns: TABLE_COLUMNS[table],
    protectedColumns: PROTECTED_COLUMNS[table as keyof typeof PROTECTED_COLUMNS] ?? [],
    uniqueConstraints: UNIQUE_CONSTRAINTS[table as keyof typeof UNIQUE_CONSTRAINTS] ?? [],
    appendOnly: APPEND_ONLY_TABLES.includes(table as (typeof APPEND_ONLY_TABLES)[number]),
    adminOnly: ADMIN_ONLY_TABLES.includes(table as (typeof ADMIN_ONLY_TABLES)[number]),
  };
}

export type RoleKey =
  | "owner"
  | "super_admin"
  | "trust_safety_admin"
  | "legal_admin"
  | "privacy_admin_dpo"
  | "security_admin"
  | "finance_admin"
  | "support_admin"
  | "research_admin"
  | "zone_admin"
  | "read_only_auditor";

export const SYSTEM_ROLE_KEYS = [
  "owner",
  "super_admin",
  "trust_safety_admin",
  "legal_admin",
  "privacy_admin_dpo",
  "security_admin",
  "finance_admin",
  "support_admin",
  "research_admin",
  "zone_admin",
  "read_only_auditor",
] as const satisfies readonly RoleKey[];
